// <auto-generated />
using System;
using DesafioTarget.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioTarget.Api.Migrations
{
    [DbContext(typeof(DesafioTargetDbContext))]
    [Migration("20261006003224_CriarEstruturaEstoque")]
    partial class CriarEstruturaEstoque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesafioTarget.Api.Data.MovimentacaoEstoqueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("EstoqueAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueFinal")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RealizadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProduto");

                    b.ToTable("MovimentacoesEstoque", (string)null);
                });

            modelBuilder.Entity("DesafioTarget.Api.Data.ProdutoEstoqueEntity", b =>
                {
                    b.Property<int>("CodigoProduto")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.HasKey("CodigoProduto");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("DesafioTarget.Api.Data.MovimentacaoEstoqueEntity", b =>
                {
                    b.HasOne("DesafioTarget.Api.Data.ProdutoEstoqueEntity", null)
                        .WithMany()
                        .HasForeignKey("CodigoProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
